import type { Metadata } from "next";
import "@/styles/shared/_base.scss"
import "@/styles/shared/_components.scss"
import "@/styles/_base.scss"
import "@/styles/_components.scss"

export const metadata: Metadata = {
  title: "Next Starter Kit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
